### ISSUE TITLE
crowdin.yml contents not matching Crowdin website configuration

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1986]
Files mentioned in /crowdin.yml file:
```yml
files:
  - source: /po/mmex.pot
    translation: /po/%locale_with_underscore%.po
```

Crowdin web interface:
* master
  * po
    * mmex.po
* docs
  * budget.html
  * grm.html
  * index.html
  * stocks_and_shares.html

What is the purpose of crowdin.yml file? Can we change project settings from git repo?
