### ISSUE TITLE
Make MMEX easier to build in a distro-agnostic way

### ISSUE THREAD

**Issue by joshua-stone** [moneymanagerex/moneymanagerex#5943]
Currently I'm having issues building MMEX as a flatpak which doesn't expose much information about the underlying build host:

```
$ flatpak run org.flatpak.Builder --install --user --force-clean _build org.moneymanagerex.MoneyManagerEx.yml

<snip>

-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.40.0") 
CMake Error at CMakeLists.txt:136 (message):
  Could not find a GNU/Linux distribution info


-- Found compile cache tool: /usr/bin/ccache (found version "4.8")
-- Found wxWidgets: -L/app/lib;-pthread;;;/app/lib/libwx_gtk3u_qa-3.2.a;/app/lib/libwx_gtk3u_aui-3.2.a;/app/lib/libwx_gtk3u_stc-3.2.a;/app/lib/libwx_gtk3u_webview-3.2.a;/app/lib/libwx_gtk3u_html-3.2.a;/app/lib/libwx_gtk3u_core-3.2.a;/app/lib/libwx_baseu_xml-3.2.a;/app/lib/libwx_baseu-3.2.a;-lgthread-2.0;-pthread;-lX11;-lXxf86vm;-lSM;-lgtk-3;-lgdk-3;-lpangocairo-1.0;-latk-1.0;-lgio-2.0;-lgdk_pixbuf-2.0;-lcairo-gobject;-lcairo;-lXtst;-lpangoft2-1.0;-lpango-1.0;-lgobject-2.0;-lharfbuzz;-lglib-2.0;-lfreetype;-lfontconfig;-lwxscintilla-3.2;-lexpat;-lpcre2-32;-lpng;-ljpeg;-lz;-lcurl;-lm (found suitable version "3.2.2", minimum required is "2.9.2") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.9.4") 
-- Checking for one of the modules 'libcurl'
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.86.0-DEV")
-- Module support is disabled.
-- Version: 8.1.1
-- Build type: 
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Found RapidJSON: /run/build/moneymanagerex/3rd/rapidjson/include
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Performing Test Wduplicated-cond
-- Performing Test Wduplicated-cond - Success
-- Performing Test Wduplicated-branches
-- Performing Test Wduplicated-branches - Success
-- Performing Test Wnull-dereference
-- Performing Test Wnull-dereference - Success
-- Performing Test Wlogical-op
-- Performing Test Wlogical-op - Success
-- Performing Test Wuseless-cast
-- Performing Test Wuseless-cast - Success
CMake Warning at CMakeLists.txt:727 (message):
  Unknown Linux distribution - generating generic package.


-- 
-- MMEX configuration summary
-- ==========================
-- Version        : 1.6.3
-- Commit         : 48d8562 (2023-01-31)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /app
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 6.2.15-300.fc38.x86_64
-- .
-- 
-- CMake 3.26.3
-- GNU Make 4.3
-- ccache 4.8
-- GNU 12.2.0
-- wxWidgets 3.2.2
-- wxSQLite3 4.9.1
-- Lua 5.3.5
-- curl 7.86.0-DEV
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring incomplete, errors occurred!
Error: module moneymanagerex: Child process exited with code 1
```

Build manifest `org.moneymanagerex.MoneyManagerEx.yml`:

```yaml
app-id: org.moneymanagerex.MoneyManagerEx
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: moneymanagerex
finish-args:
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --filesystem=home
  - --share=ipc
modules:
  - name: wxWidgets
    config-opts:
      - --disable-shared
      - --enable-cxx11
      - --with-cxx=11
      - --without-libtiff
    build-options:
      cxxflags: "-std=c++0x"
    sources:
      - type: archive
        url: https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.1.tar.bz2
        sha256: dffcb6be71296fff4b7f8840eb1b510178f57aa2eb236b20da41182009242c02 
    cleanup:
      - /bin
      - /lib
      - /doc
      - /share
  - name: lsb-release-compat
    buildsystem: simple
    build-commands:
      - make install PREFIX=/app
    sources:
      - type: git
        url: https://gitlab.com/nanonyme/lsb-release-compat.git
        commit: 5751a93f4cd3885a9c3c92aa86026255851ad670
  - name: moneymanagerex
    buildsystem: cmake
    sources:
      - type: git
        url: https://github.com/moneymanagerex/moneymanagerex
        tag: v1.6.3
```

I'm not sure what to do short of patching `CMakeLists.txt`. If this could be built as a flatpak then there could be path to [flathub app submission](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by ovari** [comment]
https://discourse.flathub.org/t/mmex-money-manager-request/3734

**Comment by joshua-stone** [comment]
I've gotten a little bit further building this, using build options from the [Dockerfiles](https://github.com/moneymanagerex/moneymanagerex/blob/master/dockers/fedora.36/Dockerfile):

**cmake.patch:**

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e0b051270..fb42d1f40 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -128,6 +128,9 @@ if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
                 OUTPUT_VARIABLE LINUX_DISTRO_REL
                 OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
             set(LINUX_DISTRO "Arch")
+        elseif(EXISTS /etc/os-release)
+            cmake_host_system_information(RESULT LINUX_DISTRO QUERY DISTRIB_NAME)
+            cmake_host_system_information(RESULT LINUX_DISTRO_REL QUERY DISTRIB_VERSION)
         else()
             message(SEND_ERROR "lsb_release tool not found.")
         endif()
```

**org.moneymanagerex.MoneyManagerEx.yml:**

```yaml
app-id: org.moneymanagerex.MoneyManagerEx
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: moneymanagerex
finish-args:
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --filesystem=home
  - --share=ipc
modules:
  - name: unifdef
    no-autogen: true
    make-install-args:
      - prefix=/app
    sources:
      - type: archive
        url: https://dotat.at/prog/unifdef/unifdef-2.12.tar.xz
        sha256: 43ce0f02ecdcdc723b2475575563ddb192e988c886d368260bc0a63aee3ac400
        x-checker-data:
          type: anitya
          project-id: 5046
          url-template: https://dotat.at/prog/unifdef/unifdef-$version.tar.xz
  - name: libavif
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=None
      - -DAVIF_CODEC_DAV1D=ON
    sources:
      - type: archive
        url: https://github.com/AOMediaCodec/libavif/archive/v0.11.1/libavif-0.11.1.tar.gz
        sha256: 0eb49965562a0e5e5de58389650d434cff32af84c34185b6c9b7b2fccae06d4e
        x-checker-data:
          type: json
          url: https://api.github.com/repos/AOMediaCodec/libavif/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag | sub("^[vV]"; "")
          url-query: '"https://github.com/AOMediaCodec/libavif/archive/\($tag)/libavif-\($version).tar.gz"'
  - name: libwpe
    buildsystem: meson
    builddir: true
    config-opts:
      - --buildtype=plain
    sources:
      - type: archive
        url: https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.14.1/libwpe-1.14.1.tar.xz
        sha256: b1d0cdcf0f8dbb494e65b0f7913e357106da9a0d57f4fbb7b9d1238a6dbe9ade
        x-checker-data:
          type: json
          url: https://api.github.com/repos/WebPlatformForEmbedded/libwpe/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag
          url-query: '"https://github.com/WebPlatformForEmbedded/libwpe/releases/download/\($tag)/libwpe-\($version).tar.xz"'
  - name: wpebackend-fdo
    buildsystem: meson
    builddir: true
    config-opts:
      - --buildtype=plain
    sources:
      - type: archive
        url: https://github.com/Igalia/WPEBackend-fdo/releases/download/1.14.2/wpebackend-fdo-1.14.2.tar.xz
        sha256: 93c9766ae9864eeaeaee2b0a74f22cbca08df42c1a1bdb55b086f2528e380d38
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Igalia/WPEBackend-fdo/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag
          url-query: '"https://github.com/Igalia/WPEBackend-fdo/releases/download/\($tag)/wpebackend-fdo-\($version).tar.xz"'
  - name: webkitgtk
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=None
      - -DPORT=GTK
      - -DUSE_LIBSECRET=OFF
      - -DUSE_WOFF2=OFF
      - -DENABLE_BUBBLEWRAP_SANDBOX=OFF
      - -DENABLE_GAMEPAD=OFF
      - -DENABLE_INTROSPECTION=OFF
      - -DENABLE_SPELLCHECK=OFF
    sources:
      - type: archive
        url: https://webkitgtk.org/releases/webkitgtk-2.40.1.tar.xz
        sha256: 64e526984f8cd2161ef03ae949af99c002ff333d615e6386b460164a3c1b7ef6
        x-checker-data:
          type: html
          url: https://webkitgtk.org/releases/
          version-pattern: LATEST-STABLE-(\d[\.\d]+\d)
          url-template: https://webkitgtk.org/releases/webkitgtk-$version.tar.xz
      - type: shell
        commands:
          - sed -i 's@NAMES avif.h@NAMES avif/avif.h@' Source/cmake/FindAVIF.cmake
          - sed -i '/PATH_SUFFIXES avif/d' Source/cmake/FindAVIF.cmake
          - sed -i 's@${AVIF_INCLUDE_DIR}/avif.h@${AVIF_INCLUDE_DIR}/avif/avif.h@'
            Source/cmake/FindAVIF.cmake
  - name: wxWidgets
    config-opts:
      - --disable-shared
      - --enable-cxx11
      - --with-cxx=11
      - --enable-webview
      - --with-gtk=3
      - --enable-unicode
      - --enable-intl
    sources:
       - type: archive
         url: https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.7/wxWidgets-3.1.7.tar.bz2
         sha256: 3d666e47d86192f085c84089b850c90db7a73a5d26b684b617298d89dce84f19
  - name: moneymanagerex
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DwxWidgets_INCLUDE_DIRS=/app/include/wx-3.1;/app/lib/wx/include/gtk3-unicode-static-3.1
    sources:
      - type: git
        url: https://github.com/moneymanagerex/moneymanagerex
        tag: v1.6.3
      - type: patch
        path: cmake.patch
```

I'm still having issues building it:

```
In file included from /run/build/moneymanagerex/src/general_report_manager.cpp:21:
/run/build/moneymanagerex/src/general_report_manager.h:101:22: error: ‘wxWebViewEvent’ has not been declared
  101 |     void OnNewWindow(wxWebViewEvent& evt);
      |                      ^~~~~~~~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.h:106:5: error: ‘wxWebView’ does not name a type
  106 |     wxWebView* browser_;
      |     ^~~~~~~~~
In file included from /run/build/moneymanagerex/src/model/Model_Account.h:26,
                 from /run/build/moneymanagerex/src/model/allmodel.h:21,
                 from /run/build/moneymanagerex/src/filtertrans.h:22,
                 from /run/build/moneymanagerex/src/filtertrans.cpp:21:
/run/build/moneymanagerex/src/model/Model_Checking.h: In instantiation of ‘void std::__new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = Model_Checking::Full_Data; _Args = {const Model_Checking::Full_Data&}; _Tp = Model_Checking::Full_Data]’:
/usr/include/c++/12.2.0/bits/alloc_traits.h:516:17:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = Model_Checking::Full_Data; _Args = {const Model_Checking::Full_Data&}; _Tp = Model_Checking::Full_Data; allocator_type = std::allocator<Model_Checking::Full_Data>]’
/usr/include/c++/12.2.0/bits/stl_vector.h:1281:30:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = Model_Checking::Full_Data; _Alloc = std::allocator<Model_Checking::Full_Data>; value_type = Model_Checking::Full_Data]’
/run/build/moneymanagerex/src/filtertrans.cpp:149:37:   required from here
/run/build/moneymanagerex/src/model/Model_Checking.h:42:12: warning: implicitly-declared ‘DB_Table_CHECKINGACCOUNT_V1::Data::Data(const DB_Table_CHECKINGACCOUNT_V1::Data&)’ is deprecated [-Wdeprecated-copy]
   42 |     struct Full_Data: public Data
      |            ^~~~~~~~~
In file included from /run/build/moneymanagerex/src/model/Model_Checking.h:23:
/run/build/moneymanagerex/src/db/DB_Table_Checkingaccount_V1.h:372:15: note: because ‘DB_Table_CHECKINGACCOUNT_V1::Data’ has user-provided ‘DB_Table_CHECKINGACCOUNT_V1::Data& DB_Table_CHECKINGACCOUNT_V1::Data::operator=(const DB_Table_CHECKINGACCOUNT_V1::Data&)’
  372 |         Data& operator=(const Data& other)
      |               ^~~~~~~~
In file included from /usr/include/c++/12.2.0/x86_64-unknown-linux-gnu/bits/c++allocator.h:33,
                 from /usr/include/c++/12.2.0/bits/allocator.h:46,
                 from /usr/include/c++/12.2.0/vector:61,
                 from /run/build/moneymanagerex/src/model/Model.h:21,
                 from /run/build/moneymanagerex/src/model/Model_Account.h:23:
/usr/include/c++/12.2.0/bits/new_allocator.h:175:11: note: synthesized method ‘Model_Checking::Full_Data::Full_Data(const Model_Checking::Full_Data&)’ first required here
  175 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 58%] Building CXX object src/CMakeFiles/mmex.dir/mmcustomdata.cpp.o
/run/build/moneymanagerex/src/general_report_manager.cpp: In constructor ‘mmGeneralReportManager::mmGeneralReportManager(wxWindow*, wxSQLite3Database*)’:
/run/build/moneymanagerex/src/general_report_manager.cpp:237:7: error: class ‘mmGeneralReportManager’ does not have any field named ‘browser_’
  237 |     , browser_(nullptr)
      |       ^~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::createOutputTab(wxNotebook*, int)’:
/run/build/moneymanagerex/src/general_report_manager.cpp:421:5: error: ‘browser_’ was not declared in this scope
  421 |     browser_ = wxWebView::New();
      |     ^~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp:421:16: error: ‘wxWebView’ has not been declared
  421 |     browser_ = wxWebView::New();
      |                ^~~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp:428:43: error: ‘wxWebViewHandler’ was not declared in this scope; did you mean ‘wxEvtHandler’?
  428 |     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
      |                                           ^~~~~~~~~~~~~~~~
      |                                           wxEvtHandler
/run/build/moneymanagerex/src/general_report_manager.cpp:428:59: error: template argument 1 is invalid
  428 |     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
      |                                                           ^
/run/build/moneymanagerex/src/general_report_manager.cpp:428:65: error: expected type-specifier before ‘wxWebViewFSHandler’
  428 |     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
      |                                                                 ^~~~~~~~~~~~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp:430:10: error: ‘wxEVT_WEBVIEW_NEWWINDOW’ was not declared in this scope; did you mean ‘wxEVT_LEAVE_WINDOW’?
  430 |     Bind(wxEVT_WEBVIEW_NEWWINDOW, &mmGeneralReportManager::OnNewWindow, this, mmID_BROWSER);
      |          ^~~~~~~~~~~~~~~~~~~~~~~
      |          wxEVT_LEAVE_WINDOW
/run/build/moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnUpdateReport(wxCommandEvent&)’:
/run/build/moneymanagerex/src/general_report_manager.cpp:698:9: error: ‘browser_’ was not declared in this scope
  698 |         browser_->SetPage(report->DESCRIPTION, "");
      |         ^~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnRun(wxCommandEvent&)’:
/run/build/moneymanagerex/src/general_report_manager.cpp:714:9: error: ‘browser_’ was not declared in this scope
  714 |         browser_->ClearBackground();
      |         ^~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnSelChanged(wxTreeEvent&)’:
/run/build/moneymanagerex/src/general_report_manager.cpp:826:9: error: ‘browser_’ was not declared in this scope
  826 |         browser_->SetPage(description, "");
      |         ^~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::showHelp()’:
/run/build/moneymanagerex/src/general_report_manager.cpp:1086:5: error: ‘browser_’ was not declared in this scope
 1086 |     browser_->LoadURL(url);
      |     ^~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp: At global scope:
/run/build/moneymanagerex/src/general_report_manager.cpp:1262:6: error: variable or field ‘OnNewWindow’ declared void
 1262 | void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
      |      ^~~~~~~~~~~~~~~~~~~~~~
/run/build/moneymanagerex/src/general_report_manager.cpp:1262:42: error: ‘wxWebViewEvent’ was not declared in this scope; did you mean ‘wxDataViewEvent’?
 1262 | void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
      |                                          ^~~~~~~~~~~~~~
      |                                          wxDataViewEvent
/run/build/moneymanagerex/src/general_report_manager.cpp:1262:58: error: ‘evt’ was not declared in this scope; did you mean ‘ecvt’?
 1262 | void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
      |                                                          ^~~
      |                                                          ecvt
```
